lang_dict = {
	"🇧🇪 Nederlands":"NL",
	"🇬🇧 English":"EN"
}

content = {

	###############
	#
	# NAVIGATION SIDEBAR
	#
	###############
	"sidebar_title_NL":"Navigeer naar:",
	"sidebar_title_EN":"Go to:",
	"sidebar_button_welcome_NL":"# 🎈 Welkom",
	"sidebar_button_welcome_EN":"# 🎈 Welcome",
	"sidebar_button_request_NL":"# 📚 Maak een verhaaltje",
	"sidebar_button_request_EN":"# 📚 Create a story",
	"sidebar_button_faq_NL":"# ❓ FAQ",
	"sidebar_button_faq_EN":"# ❓ FAQ",
	"sidebar_button_examples_NL":"# ✎ Voorbeelden",
	"sidebar_button_examples_EN":"# ✎ Examples",
	"sidebar_button_support_NL":"# ✨ Steun ons",
	"sidebar_button_support_EN":"# ✨ Support us",
	
	###############
	#
	# WELCOME
	#
	###############
	"subtitle_welcome_NL":"## Gepersonaliseerde verhaaltjes voor het slapen gaan.",
	"subtitle_welcome_EN":"## Personalized stories to read before bedtime.",
	
	"subtitle_welcome_help_NL":"Verhaaltjes worden gemaakt aan de hand van ChatGPT-4o en illustraties aan de hand van DALL-E 3, beiden [modellen die door OpenAI aangeboden worden](https://platform.openai.com/docs/models).",
	"subtitle_welcome_help_EN":"Stories are created using ChatGPT-4o and illustrations using DALL-E 3, both [models that are provided by OpenAI](https://platform.openai.com/docs/models).",
	
	"welcome_request_from_welcome_top_NL":"# 🌟 Maak een verhaaltje 🌟",
	"welcome_request_from_welcome_top_EN":"# 🌟 Create a story 🌟",
	
	"welcome_intro_NL":"""
## Welkom!
AI bedtime stories is een geautomatiseerde service die door middel van artificiële intelligentie gepersonaliseerde verhaaltjes en illustraties kan maken. Op basis van de gegevens die jij ingeeft (naam & kenmerken van je kind en andere elementen die je graag in het verhaal wil verwerken), zal een kort verhaaltje met bijpassende illustratie naar jouw e-mail adres gestuurd worden.

Het wordt pas echt magisch als je aan je kindje vraagt wat hij/zij graag in het verhaaltje zou willen verwerken! Hun fantasie rijkt vaak duizend maal verder dan die van ons!
	""",
	"welcome_intro_EN":"""
## Welcome!
AI bedtime stories is an automated service that can create personalized stories and illustrations through artificial intelligence. Based on the data you provide (name & characteristics of your child and other elements you would like to incorporate into the story), a short story with a matching illustration will be sent to your email address.

It becomes truly magical when you ask your child what he/she would like to include in the story! Their imagination often reaches a thousand times further than ours!
	""",

	"welcome_how_does_it_work_NL":"""
## Hoe werkt het?
Een verhaaltje aanvragen doe je zo:
  1. klik hieronder of in de navigatiebalk (links) op "Maak een verhaaltje"
  2. Vul het formulier in door de vragen (met zoveel mogelijk details) te beantwoorden en druk op "Submit form".
  3. Je zal binnen 24u (mogelijks al een stuk sneller) een e-mail ontvangen waarin je je persoonlijke verhaaltje met bijgevoegde illustratie kan terugvinden.

Je kan hieronder ook doorklikken om veelgestelde vragen te overlopen, of om een voorbeeldje te zien van wat je kan verwachten!
	""",
	"welcome_how_does_it_work_EN":"""
## How does it work?
Requesting a story is done like this:
  1. click below or in the navigation bar (left) on "Create a story"
  2. Fill in the form by answering the questions (with as many details as possible) and press "Submit form".
  3. You will receive an email within 24 hours (possibly much sooner) containing your personal story with attached illustration.

You can also click below to go over frequently asked questions, or to see an example of what you can expect!
	""",
	
	"welcome_info_disclaimer_NL": """
        Disclaimer:
        De verhaaltjes en bijgevoegde illustraties worden automatisch via artificiële intelligentie gemaakt, op basis van de input die jij doorgeeft. Wij kunnen nooit verantwoordelijk gehouden worden voor onverwachte of aanstootgevende uitkomsten!
    """,
    "welcome_info_disclaimer_EN": """
        Disclaimer:
        The stories and accompanying illustrations are automatically generated by artificial intelligence based on the input you provide. We can never be held responsible for unexpected or offensive outcomes!
    """,
    "welcome_request_from_welcome_NL": "Maak een verhaaltje",
    "welcome_request_from_welcome_EN": "Create a story",
    "welcome_faq_from_welcome_NL": "Frequently Asked Questions",
    "welcome_faq_from_welcome_EN": "Frequently Asked Questions",
    "welcome_examples_from_welcome_NL": "Voorbeelden",
    "welcome_examples_from_welcome_EN": "Examples",
    "welcome_expectation_details_NL": """
## Wat mag ik verwachten?

Als je het formulier invult en indient zal er automatisch een verhaaltje gemaakt worden dat je als een pdf in je inbox zal kunnen terugvinden. Je kindje zal ongetwijfeld genieten van de inhoud van het verhaal en de bijgevoegde illustratie, maar dit bestand heeft geen speciale opmaak.

Je kan tegen betaling en op aanvraag het verhaaltje ook digitaal(!) in een meer **opgemaakte versie** ontvangen, zoals hieronder staat afgebeeld. Een leuk idee om later af te drukken en in te kaderen, eventueel als cadeau voor je nieuwe nichtje/neefje/mete- of petekindje, ...!

Daarvoor vragen wij een bijdrage van **3,95 euro**. Bij interesse kan je dit op de volgende manier aanvragen:

  * [**Stuur me een e-mail**](mailto:genaibedtimestories@gmail.com) (antwoord niet op de originele geautomatiseerde email, deze komt niet van het juiste email adres!)
  * Voeg in de attachment het pdf bestand toe dat je origineel hebt ontvangen, en vermeld duidelijk dat je graag een opgemaakte versie wil ontvangen.
  * Ik zal zo snel mogelijk contact opnemen met details over de betaling.
  * Van zodra de betaling ontvangen is stuur ik je **digitaal(!)** een opgemaakte versie door. (Wij printen niets af en sturen niets met de post op!)
    """,
    "welcome_expectation_details_EN": """
## What can I expect?

When you fill out and submit the form, a story will be automatically created and you will find it as a PDF in your inbox. Your child will undoubtedly enjoy the content of the story and the accompanying illustration, but this file has no special formatting.

For a fee and upon request, you can also receive the story digitally(!) in a more **formatted version** as shown below. A nice idea to print later and frame, possibly as a gift for your new niece/nephew/godchild, ...!

For this, we ask a contribution of **3,95 euros**. If interested, you can request this in the following way:

  * [**Send me an email**](mailto:genaibedtimestories@gmail.com) (do not reply to the original automated email, it does not come from the correct email address!)
  * Attach the PDF file you originally received, and clearly state that you would like to receive a formatted version.
  * I will contact you as soon as possible with details about the payment.
  * Once the payment is received, I will send you **digitally(!)** a formatted version. (We do not print anything and send nothing by mail!)
    """,
    "welcome_support_heading_NL": "## Wil je dit initiatief graag steunen?",
    "welcome_support_heading_EN": "## Would you like to support this initiative?",

    "welcome_automated_free_NL": "<h3 style='text-align: center; color: black;'>Geautomatiseerd (gratis)</h3>",
    "welcome_automated_free_EN": "<h3 style='text-align: center; color: black;'>Automated (free)</h3>",

    "welcome_request_paid_NL": "<h3 style='text-align: center; color: black;'>Op aanvraag (betalend)</h3>",
    "welcome_request_paid_EN": "<h3 style='text-align: center; color: black;'>On request (paid)</h3>",
    "welcome_support_from_welcome_NL": "# 🌟 Kijk hier hoe je ons kan steunen! 🌟",
    "welcome_support_from_welcome_EN": "# 🌟 See here how you can support us! 🌟",

	###############
	#
	# REQUEST
	#
	###############
	
	"request_title_NL": "# Vraag een verhaaltje aan",
    "request_title_EN": "# Request a Story",

    "request_info_NL": """
Vul onderstaande informatie zo nauwkeurig mogelijk in. Hoe meer details je meegeeft, hoe beter de kwaliteit van het verhaal en de bijhorende illustratie zal zijn.
    """,
    "request_info_EN": """
Please fill in the information below as accurately as possible. The more details you provide, the better the quality of the story and the accompanying illustration will be.
    """,
	
	###############
	#
	# FAQ
	#
	###############
	
	"faq_title_NL": "Frequently Asked Questions",
    "faq_title_EN": "Frequently Asked Questions",

    "faq_expander1_title_NL": "Ik wacht al meer dan 24u maar heb nog geen email ontvangen?",
    "faq_expander1_title_EN": "I have been waiting for more than 24 hours but haven't received any email?",
    "faq_expander1_content_NL": '''
Het spijt me dat je nog geen verhaaltje hebt ontvangen, normaal zou je binnen 24u zeker een email moeten hebben ontvangen. Het automatisch genereren van een verhaal en bijgevoegde illustratie is afhankelijk van verschillende externe services. Er kan altijd iets mis lopen, zowel bij de externe services als ergens anders. Wat je alvast kan proberen is het volgende:
  * Kijk even je spam na
  * Kijk na of je inbox niet vol zit
  * Probeer het gewoon nog een keer, misschien lukt het deze keer wel

Als je toch nog steeds niets ontvangt, aarzel dan niet om contact op te nemen door [een e-mail te sturen](mailto:genaibedtimestories@gmail.com)!
    ''',
    "faq_expander1_content_EN": '''
I'm sorry you haven't received your story yet, normally you should have received an email within 24 hours. The automatic generation of a story and accompanying illustration depends on various external services. Something can always go wrong, either with the external services or elsewhere. Here's what you can try:
  * Check your spam folder
  * Check if your inbox is not full
  * Try again, maybe it will work this time

If you still receive nothing, do not hesitate to contact us by [sending an email](mailto:genaibedtimestories@gmail.com)!
    ''',

    "faq_expander2_title_NL": "Het verhaal en/of de illustratie komen niet goed overeen met mijn beschrijving, hoe komt dat?",
    "faq_expander2_title_EN": "The story and/or illustration do not match my description, why is that?",
    "faq_expander2_content_NL": '''
Helaas hebben we weinig controle over wat de AI algoritmes genereren, en kan het soms gebeuren dat het resultaat (text of beeld) niet helemaal overeen komt met wat je zou verwachten. Het helpt om het formulier met zo veel mogelijk detail in te vullen, dus probeer het gerust nog een keer met een nieuwe, gedetailleerde beschrijving van wat je graag wil zien/horen!
    ''',
    "faq_expander2_content_EN": '''
Unfortunately, we have little control over what the AI algorithms generate, and it can sometimes happen that the result (text or image) does not quite match what you would expect. It helps to fill out the form with as much detail as possible, so feel free to try again with a new, detailed description of what you would like to see/hear!
    ''',

    "faq_expander3_title_NL": "Hoe weet ik of mijn aanvraag goed verzonden is?",
    "faq_expander3_title_EN": "How do I know if my request has been sent correctly?",
    "faq_expander3_content_NL": '''
Als je onderstaand scherm te zien krijgt weet je dat je aanvraag goed verzonden is. Er kan echter nog altijd iets mislopen in het process waardoor je toch geen email ontvangt binnen de 24u. Als dat zo zou zijn, kijk dan even naar de gerelateerde vraag hierboven.
    ''',
    "faq_expander3_content_EN": '''
If you see the screen below, you know that your request has been sent correctly. However, something can still go wrong in the process, causing you not to receive an email within 24 hours. If that is the case, please refer to the related question above.
    ''',
    
    ###############
	#
	# Examples
	#
	###############

    "examples_title_NL": "Voorbeelden",
    "examples_title_EN": "Examples",

    "examples_input_header_NL": "## Input",
    "examples_input_header_EN": "## Input",

    "examples_input_table_NL": """
    | Vraag | Antwoord|
    --------|-------- |
    | Naam | Lily |
    | Kenmerken| 2-jarig meisje met donkerbruin haar en staartje bovenop haar hoofd. Ze draagt een groene t-shirt met een smiley op. |
    | Elementen in het verhaal | Lily gaat graag naar de dierentuin. |
    | Taal | Nederlands |
    """,
    "examples_input_table_EN": """
    | Question | Answer |
    --------|-------- |
    | Name | Lily |
    | Characteristics | 2-year-old girl with dark brown hair and a ponytail on top of her head. She wears a green t-shirt with a smiley face on it. |
    | Elements in the story | Lily loves going to the zoo. |
    | Language | English |
    """,
	
	    "examples_result_header_NL": "## Resultaat",
    "examples_result_header_EN": "## Result",

    "examples_result_subheader_NL": "### Lily bij de Flamingo's",
    "examples_result_subheader_EN": "### Lily at the Flamingos",

    "examples_result_story_NL": """
Er was eens een klein meisje genaamd Lily. Ze was twee jaar oud, had donkerbruin haar dat in een grappig staartje bovenop haar hoofd stond. Lily droeg altijd haar favoriete groene t-shirt met een grote smiley erop. Ze vond het geweldig om naar de dierentuin te gaan en was altijd vol enthousiasme.

Op een zonnige dag mocht Lily samen met haar ouders naar de zoo. Ze huppelde vrolijk van het ene dierenverblijf naar het andere. Ze bewonderde de olifanten, lachte om de grappige aapjes en zwaaide naar de majestueuze leeuwen.

Toen gebeurde er iets spannends. Terwijl Lily naar de kleurrijke papegaaien keek, liep ze per ongeluk een beetje te ver weg van haar ouders. Plotseling stond ze alleen bij het hek van de flamingo's. Lily keek om zich heen, maar zag haar ouders nergens. Haar hartje begon sneller te kloppen.

Net op dat moment hoorde ze een zachte stem: "Lily, waar ben je?" Het was haar moeder! Met een opgelucht gevoel rende ze naar de stem toe en viel in de warme armen van haar moeder. Haar ouders waren gewoon een paar meter verderop geweest en hadden haar de hele tijd in de gaten gehouden.

Die avond, veilig in haar bedje, droomde Lily over alle prachtige dieren en wist ze dat alles altijd goed zou komen zolang ze dicht bij haar ouders bleef. En met dat geruststellende gevoel, viel ze snel in slaap.
    """,
    "examples_result_story_EN": """
Once upon a time, there was a little girl named Lily. She was two years old, had dark brown hair tied in a cute ponytail on top of her head. Lily always wore her favorite green t-shirt with a big smiley face on it. She loved going to the zoo and was always full of enthusiasm.

On a sunny day, Lily got to go to the zoo with her parents. She cheerfully hopped from one animal enclosure to another. She admired the elephants, laughed at the funny monkeys, and waved at the majestic lions.

Then something exciting happened. While Lily was looking at the colorful parrots, she accidentally wandered a bit too far from her parents. Suddenly, she found herself alone at the flamingo's fence. Lily looked around but couldn't see her parents anywhere. Her heart started to beat faster.

Just at that moment, she heard a soft voice: "Lily, where are you?" It was her mother! With a relieved feeling, she ran towards the voice and fell into her mother's warm arms. Her parents had just been a few meters away and had been watching her all the time.

That evening, safely in her bed, Lily dreamed about all the wonderful animals and knew that everything would always be alright as long as she stayed close to her parents. And with that comforting thought, she quickly fell asleep.
    """,
    
    "examples_formatted_version_header_NL": "## Opgemaakte versie (op aanvraag en betalend)",
    "examples_formatted_version_header_EN": "## Formatted Version (on request and paid)",

    "examples_formatted_version_description_NL": """
Je kan tegen betaling en op aanvraag het verhaaltje ook digitaal(!) in een meer **opgemaakte versie** ontvangen, zoals hieronder staat afgebeeld. Een leuk idee om later af te drukken en in te kaderen, eventueel als cadeau voor je nieuwe nichtje/neefje/mete- of petekindje!

Daarvoor vragen wij een bijdrage van **3,95 euro**. Bij interesse kan je dit op de volgende manier aanvragen:

  * [**Stuur me een e-mail**](mailto:genaibedtimestories@gmail.com) (antwoord niet op de originele geautomatiseerde email, deze komt niet van het juiste email adres!)
  * Voeg in de attachment het pdf bestand toe dat je origineel hebt ontvangen, en vermeld duidelijk dat je graag een opgemaakte versie wil ontvangen.
  * Ik zal zo snel mogelijk contact opnemen met details over de betaling.
  * Van zodra de betaling ontvangen is stuur ik je **digitaal(!)** een opgemaakte versie door. (Wij printen niets af en sturen niets met de post op!)
    """,
    "examples_formatted_version_description_EN": """
You can request and receive the story digitally in a more **formatted version** for a fee, as shown below. A great idea to print later and frame, possibly as a gift for your new niece/nephew/godchild!

For this, we ask for a contribution of **3,95 euros**. If interested, you can request it in the following way:

  * [**Send me an email**](mailto:genaibedtimestories@gmail.com) (do not reply to the original automated email, it does not come from the correct email address!)
  * Attach the PDF file you originally received, and clearly state that you would like to receive a formatted version.
  * I will contact you as soon as possible with details about the payment.
  * Once the payment is received, I will send you a **digital(!)** formatted version. (We do not print anything or send anything by mail!)
    """,
    
    ###############
	#
	# Support
	#
	###############
    
    "support_title_NL": "# Wil je dit initiatief graag steunen?",
    "support_title_EN": "# Would you like to support this initiative?",

    "support_description_NL": """
In eerste instantie is het mijn doel om **een lach te toveren op de gezichten van jullie kindjes**. Vandaar is de service voorlopig helemaal gratis! In tweede instantie hoop ik dat ik ook het level van jullie als ouder wat eenvoudiger maak tijdens de avondroutine voor het slapen gaan.

Als dat is gelukt, en je wil dit initiatief graag steunen, dan kan dat op twee manieren:
  * [**Stuur me een e-mail**](mailto:genaibedtimestories@gmail.com) met je hopelijke leuke ervaring en eventuele constructieve feedback, dat zal een lach op mijn gezicht toveren!
  * Je kan ook een vrijwillige [**donatie maken via deze link**](https://www.paypal.com/donate/?hosted_button_id=U6D6FC5LSCPWY) of onderstaande knop of QR code. Dit geld zal ik gebruiken om de kosten te dekken die nodig zijn om dit initiatief te onderhouden. Als er dan nog iets over blijft gaat dat rechtstreeks in het spaarvarkentje van mijn twee dochtertjes.
    """,
    "support_description_EN": """
First and foremost, my goal is to **bring a smile to your children's faces**. Therefore, the service is currently completely free! Secondly, I hope to make the evening routine before bedtime a bit easier for you as parents.

If that succeeds, and you would like to support this initiative, you can do so in two ways:
  * [**Send me an email**](mailto:genaibedtimestories@gmail.com) with your hopefully enjoyable experience and any constructive feedback, which will bring a smile to my face!
  * You can also make a voluntary [**donation through this link**](https://www.paypal.com/donate/?hosted_button_id=U6D6FC5LSCPWY) or the button or QR code below. This money will be used to cover the costs necessary to maintain this initiative. If there is anything left over, it will go directly into the piggy bank of my two little daughters.
    """,

    "support_donate_button_NL": "🌟  **Steun ons**  🌟",
    "support_donate_button_EN": "🌟  **Support us**  🌟",

    "support_qr_caption_NL": "Doneer door deze QR code te scannen",
    "support_qr_caption_EN": "Donate by scanning this QR code",

}